/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { createDecorator } from 'vs/platform/instantiation/common/instantiation';
import { Event } from 'vs/base/common/event';

export const ILLMProviderService = createDecorator<ILLMProviderService>('llmProviderService');

/**
 * Configuration for an LLM provider.
 */
export interface LLMProviderConfig {
	/** Unique identifier for this provider (e.g. "openai", "aphrodite", "local"). */
	readonly id: string;
	/** Human-readable display name. */
	readonly displayName: string;
	/** Base URL for the API endpoint. */
	readonly baseUrl: string;
	/** Model identifier (e.g. "gpt-4o", "DialoGPT-medium"). */
	readonly model: string;
	/** Maximum context window size in tokens. */
	readonly maxContextLength: number;
	/** Optional API key (empty for local models). */
	readonly apiKey?: string;
}

/**
 * Request to generate a completion from the LLM.
 */
export interface LLMCompletionRequest {
	/** The prompt or system message. */
	systemPrompt: string;
	/** The user query / message. */
	userMessage: string;
	/** Optional thinking context to include. */
	thinkingContext?: string;
	/** Maximum tokens in the response. */
	maxTokens?: number;
	/** Temperature for sampling (0-2). */
	temperature?: number;
}

/**
 * Response from an LLM completion.
 */
export interface LLMCompletionResponse {
	/** The generated text. */
	content: string;
	/** The provider that generated this response. */
	providerId: string;
	/** Token usage statistics (when available). */
	usage?: {
		promptTokens: number;
		completionTokens: number;
		totalTokens: number;
	};
	/** Whether this was generated by the built-in fallback. */
	isFallback: boolean;
}

/**
 * Pluggable LLM provider service for Zone-Cog cognitive processing.
 *
 * Supports multiple backends: OpenAI-compatible APIs, Aphrodite Engine,
 * local models, and a built-in rule-based fallback. Providers can be
 * registered and switched at runtime.
 */
export interface ILLMProviderService {
	readonly _serviceBrand: undefined;

	/** Fired when the active provider changes. */
	readonly onDidChangeProvider: Event<LLMProviderConfig>;

	/** Fired when a provider becomes available or unavailable. */
	readonly onDidChangeAvailability: Event<{ providerId: string; available: boolean }>;

	/**
	 * Register a new LLM provider configuration.
	 * @returns true if the provider was registered (false if id already exists).
	 */
	registerProvider(config: LLMProviderConfig): boolean;

	/**
	 * Remove a previously registered provider.
	 */
	unregisterProvider(id: string): boolean;

	/**
	 * Get all registered provider configurations.
	 */
	getProviders(): LLMProviderConfig[];

	/**
	 * Get the currently active provider configuration.
	 */
	getActiveProvider(): LLMProviderConfig;

	/**
	 * Switch the active provider.
	 * @returns true if the switch succeeded.
	 */
	setActiveProvider(id: string): boolean;

	/**
	 * Generate a completion using the active provider.
	 * Falls back to the built-in provider on errors.
	 */
	complete(request: LLMCompletionRequest): Promise<LLMCompletionResponse>;

	/**
	 * Check if an external LLM provider is available (non-fallback).
	 */
	isExternalProviderActive(): boolean;
}
